info:
  description: Default Description
  url: https://github.com/attosoft-corp/atto-config-server
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
      shouldFetchRegistry: false
      ValidateCertificates: false
