eureka:
  client:
    serviceUrl: http://atto-eureka-server.common.svc:8080/eureka/
    shouldRegisterWithEureka: true
    shouldFetchRegistry: true
    ValidateCertificates: false
  instance:
    port: 8080
    preferIpAddress: true
    prefer-ip-address: true

Logging: 
  LogLevel:
    Default: Debug
    System: Information
    Microsoft: Information
