eureka:
  client:
    serviceUrl: http://atto-eureka-server.common.svc:8080/eureka/
    shouldRegisterWithEureka: true
    shouldFetchRegistry: true
    ValidateCertificates: false
  instance:
    port: 8080

Logging:
  LogLevel:
    Default: Debug
    System: Information
    Microsoft: Information
