spring:
  application:
    name: atto-zuul-server.common.svc

eureka:
  client:
    serviceUrl:
      defaultZone: http://atto-eureka-server.common.svc:8080/eureka/

server:
  port: 8080

zuul:
  prefix: /api/attosoft-corp
  routes:
    hello-service:
      path: /server/**
      serviceId: atto-hello-service.businnes.svc
    hello-client:
      path: /client/**
      serviceId: atto-hello-client.businnes.svc