---
info:
  description: Hello-Service from joke teste

spring:
  application:
    name: atto-hello-client.businnes.svc

hystrix:
  stream:
    validate_certificates: false
  command:
    JokeCommand:
      threadPoolKeyOverride: JokeServiceTPool