info:
  description: Hello-Service this message comes from config-server in hello-service file
  exchangeSend: CRM.CustomerService.GetCustomer[CPF]
  queueSend: CRM.CustomerService.GetCustomer[CPF]
  exchangeGet: GECAD.CustomerService.GetCustomer[CPF]
  queueGet: GECAD.CustomerService.GetCustomer[CPF]

RawRabbit:
  VirtualHost: "/"
  Hostnames:
  - openshift-rabbitmq.common.svc
  Port: 5672
  Username: guest
  Password: guest
  RequestTimeout: '00:01:00'

spring:
  application:
    name: atto-hello-service.businnes.svc