info:
  description: Hello-Client this message comes from config-server in hello-client file

spring:
  application:
    name: atto-hello-client.businnes.svc

hystrix:
  stream:
    validate_certificates: false
  command:
    JokeCommand:
      threadPoolKeyOverride: JokeServiceTPool

atto-joke-config:
  Url: http://atto-hello-service:8080/